import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import { Flex, Grid, Theme } from "@radix-ui/themes";
import SideNav from "./SideNav";
import RightNav from "./RightNav";
import CreatePostTopNav from "./create-post/_components/CreatePostTopNav";
import QueryClientProvider from "./QueryClientProvider";
import AuthProvider from "./auth/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider>
          <AuthProvider>
            <Theme>
              <div className="flex">
                <div className="flex-none w-64 bg-gray-100">
                  <SideNav />
                </div>
                <main className="flex-1 bg-gray-100 items-center justify-center">
                  <CreatePostTopNav />
                  {children}
                </main>
                <div className="flex-none w-64 bg-gray-100">
                  <RightNav />
                </div>
              </div>
            </Theme>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
